# ============================================================
# _config.yml
# 
# configuration file for site wide settings
# ============================================================

#---------------------------
# Site settings
#---------------------------

title: Precious Plastic Dublin
email: info@preciousplasticdublin.org
description: "Precious Plastic Dublin is a group of environmentalists working on practical solutions to plastic waste and pollution in Dublin. As part of the Precious Plastic global movement, we aim to bring plastic recycling closer to the local community, enabling the public to transform their own waste, while demonstrating the remaining value of plastic waste."
url: https://www.preciousplasticdublin.org
baseurl: ""
locale: en
feed:
  path: feed.xml


#---------------------------
# Build settings
#---------------------------

permalink: /:categories/:title/
include: ['_pages', '_events', '.htaccess']
exclude: ['Gemfile', 'Gemfile.lock', 'node_modules', 'LICENSE.md', 'README.md', 'Gruntfile.js', 'package.json']

plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed


#---------------------------
# Style settings
#---------------------------

sass:
  sass_dir: _sass
  style: compressed

#---------------------------
# Markdown settings
#---------------------------

kramdown:
  toc_levels: 1..2
highlighter: rouge


#---------------------------
# Author settings for posts
#---------------------------

owner:
  name: Precious Plastic Dublin
  email: info@preciousplasticdublin.org
  twitter: DublinPlastic
  bio: Precious Plastic Dublin is a group of environmentalists working on practical solutions to plastic waste and pollution in Dublin. As part of the Precious Plastic global movement, we aim to bring plastic recycling closer to the local community, enabling the public to transform their own waste, while demonstrating the remaining value of plastic waste.
  avatar: logo/precious-plastic-dublin-logo-120.png
  
#---------------------------
# Social media
#---------------------------
  
facebook_url: https://www.facebook.com/preciousplasticdublin/
twitter_url: https://twitter.com/DublinPlastic
instagram_url: https://www.instagram.com/preciousplasticdublin/
